const ProductData = [
    {
        id: 1,
        imgUrl: '/products/Acacia Pure Honey.webp',
        title: 'Acacia Pure Honey',
        slug: 'acacia-pure-honey',
        shortDes: 'Honey derived from Robinia pseudoacacia flower, commonly known as the Black Locust or False Acacia tree.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi sint iusto tempora illo fugit obcaecati saepe nihil ea ipsa, suscipit architecto mollitia explicabo tempore. Voluptas consequuntur suscipit possimus! Deserunt, obcaecati.',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 2,
        imgUrl: '/products/Apple Vinegar.webp',
        title: 'Apple Vinegar',
        slug: 'apple-vinegar',
        shortDes: 'Good Quality Apple Vinegar',
        description: 'Good Quality Apple Vinegar',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 3,
        imgUrl: '/products/Apricot Flower Pure Honey.webp',
        title: 'Apricot Flower Pure Honey',
        slug: 'apricot-flower-pure-honey',
        shortDes: 'Apricot Flower Pure Honey',
        description: 'Apricot Flower Pure Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 4,
        imgUrl: '/products/Black Seed in Honey.webp',
        title: 'Black Seed in Honey',
        slug: 'black-seed-in-honey',
        shortDes: 'Black Seeds in Honey!',
        description: 'Black Seeds in Honey!',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 5,
        imgUrl: '/products/Dates Syrup.webp',
        title: 'Dates Syrup',
        slug: 'dates-syrup',
        shortDes: 'Pourable Syrup of Dates!',
        description: 'Pourable Syrup of Dates!',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 6,
        imgUrl: '/products/Egyptian Desert Herb Flower Honey.webp',
        title: 'Egyptian Desert Herb Flower Honey',
        slug: 'egyptian-desert-herb-flower-honey',
        shortDes: 'Authentic Egyptian Honey',
        description: 'Authentic Egyptian Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 7,
        imgUrl: '/products/Habbatus Sauda Royal Honey.webp',
        title: 'Habbatus Sauda Royal Honey.webp',
        slug: 'habbatus-sauda-royal-honey',
        shortDes: 'Authentic Egyptian Honey',
        description: 'Authentic Egyptian Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 8,
        imgUrl: '/products/HoneyComb with Honey.webp',
        title: 'HoneyComb with Honey.webp',
        slug: 'honeycomb-honey',
        shortDes: 'Authentic Egyptian Honey',
        description: 'Authentic Egyptian Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 9,
        imgUrl: '/products/Khalta Booster.webp',
        title: 'Khalta Booster',
        slug: 'khalta-booster',
        shortDes: 'Authentic Egyptian Honey',
        description: 'Authentic Egyptian Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 10,
        imgUrl: '/products/Nuts & Habbatus Sauda in Pure Honey.webp',
        title: 'Nuts & Habbatus Sauda in Pure Honey',
        slug: 'nuts-habbatus-sauda-in-honey',
        shortDes: 'Authentic Egyptian Honey',
        description: 'Authentic Egyptian Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 11,
        imgUrl: '/products/Ox Garlic.webp',
        title: 'Ox Garlic',
        slug: 'ox-garlic',
        shortDes: 'Authentic Egyptian Honey',
        description: 'Authentic Egyptian Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 12,
        imgUrl: '/products/Palestinian Extra Virgin Olive Oil.webp',
        title: 'Palestinian Extra Virgin Olive Oil',
        slug: 'palestinian-extra-virgin-olive-oil',
        shortDes: 'Authentic Egyptian Honey',
        description: 'Authentic Egyptian Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 13,
        imgUrl: '/products/Pomegranate Concentrate.webp',
        title: 'Pomegranate Concentrate',
        slug: 'pomegranate-concentrate',
        shortDes: 'Authentic Egyptian Honey',
        description: 'Authentic Egyptian Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 14,
        imgUrl: '/products/Pomegranate Vinegar.webp',
        title: 'Pomegranate Vinegar',
        slug: 'pomegranate-vinegar.webp',
        shortDes: 'Pomegranate Vinegar',
        description: 'Pomegranate Vinegar',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 15,
        imgUrl: '/products/Sunnah Talbinah.webp',
        title: 'Sunnah Talbinah',
        slug: 'sunnah-talbinah',
        shortDes: 'Sunnah Talbinah',
        description: 'Sunnah Talbinah',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 16,
        imgUrl: '/products/Sunnah Talbinah with Cinnamon.webp',
        title: 'Sunnah Talbinah with Cinnamon',
        slug: 'sunnah-talbinah-with-cinnamon',
        shortDes: 'Sunnah Talbinah with Cinnamon',
        description: 'Sunnah Talbinah with Cinnamony',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 17,
        imgUrl: '/products/Wild Royal Yemeni Cave Sidr Honey.webp',
        title: 'Wild Royal Yemeni Cave Sidr Honey',
        slug: 'wild-royal-yemeni-cave-sidr-honey',
        shortDes: 'Wild Royal Yemeni Cave Sidr Honey',
        description: 'Wild Royal Yemeni Cave Sidr Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    },
    {
        id: 18,
        imgUrl: '/products/Zuriat Fruit in Honey.webp',
        title: 'Zuriat Fruit in Honey',
        slug: 'zuriat-fruit-in-honey',
        shortDes: 'Zuriat Fruit in Honey',
        description: 'Zuriat Fruit in Honey',
        price: 'Please Enquire For Price',
        images: [],
        qty: 1,
        stock: 'in stock'
    }
]
export default ProductData;