import Navbar from "@/components/navbar";
import "./globals.css";
import "./media-queries.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'react-toastify/dist/ReactToastify.css';
import ToolBar from "@/components/toolbar";
import ContextProvider from "@/context";
import Footer from "@/components/footer";
import { Suspense } from "react";


export const metadata = {
  title: "Pure Essence",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <ContextProvider>
          {/* <Suspense fallback={<Loading />}> */}
          <ToolBar />
          <Navbar />
          {children}
          <Footer />
          {/* </Suspense> */}
        </ContextProvider>

      </body>
    </html >
  );
}
export function Loading() {
  return (
    <>
      <div style={{ backgroundColor: 'blue', color: 'white', height: '100vh', width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '5rem' }}>
        <h1>Loading......</h1>
      </div>
    </>
  )
}
