import Navbar from "@/components/navbar";
import "./globals.css";
import "./media-queries.css";


export const metadata = {
  title: "Pure Essence",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
